import type { Complaint, Officer, Department } from './types';

export const DEPARTMENTS: Department[] = [
  'Public Works',
  'Sanitation',
  'Electrical',
  'Water Authority',
  'Drainage Board',
];

export const CATEGORY_TO_DEPARTMENT: Record<string, Department> = {
  Potholes: 'Public Works',
  Garbage: 'Sanitation',
  Streetlight: 'Electrical',
  'Water Leakage': 'Water Authority',
  Drainage: 'Drainage Board',
};

export const OFFICERS: Officer[] = [
  { id: 'o1', name: 'Rajesh Kumar', department: 'Public Works', avatarColor: '#1e3a5f', activeTasks: 3 },
  { id: 'o2', name: 'Priya Sharma', department: 'Sanitation', avatarColor: '#0d9488', activeTasks: 2 },
  { id: 'o3', name: 'Amit Verma', department: 'Electrical', avatarColor: '#2563eb', activeTasks: 4 },
  { id: 'o4', name: 'Sneha Reddy', department: 'Water Authority', avatarColor: '#0891b2', activeTasks: 1 },
  { id: 'o5', name: 'Mohammed Ali', department: 'Drainage Board', avatarColor: '#6366f1', activeTasks: 2 },
  { id: 'o6', name: 'Kavita Nair', department: 'Public Works', avatarColor: '#1e3a5f', activeTasks: 0 },
  { id: 'o7', name: 'Arjun Singh', department: 'Sanitation', avatarColor: '#0d9488', activeTasks: 1 },
];

const now = new Date();
const daysAgo = (d: number) => {
  const dt = new Date(now);
  dt.setDate(dt.getDate() - d);
  return dt.toISOString();
};
const daysAhead = (d: number) => {
  const dt = new Date(now);
  dt.setDate(dt.getDate() + d);
  return dt.toISOString();
};

export const SAMPLE_COMPLAINTS: Complaint[] = [
  {
    id: 'CIV-2024-001',
    title: 'Large pothole near MG Road junction',
    description: 'A deep pothole has formed near the MG Road traffic signal, causing vehicles to swerve dangerously.',
    category: 'Potholes',
    location: 'MG Road, Sector 14',
    locality: 'Sector 14',
    lat: 28.4595, lng: 77.0266,
    photoUrl: null,
    status: 'In Progress',
    priority: 'High',
    department: 'Public Works',
    assignedOfficer: 'Rajesh Kumar',
    deadline: daysAhead(3),
    createdAt: daysAgo(2),
    citizenId: 'c1', citizenName: 'Rahul Mehta',
    updates: [
      { id: 'u1', status: 'Pending', message: 'Complaint registered and forwarded to Public Works department.', timestamp: daysAgo(2), by: 'Civic Pilot AI' },
      { id: 'u2', status: 'In Progress', message: 'Inspector Rajesh Kumar assigned. Site inspection scheduled.', timestamp: daysAgo(1), by: 'Admin Office' },
    ],
    aiCategoryConfidence: 0.96,
    aiPriorityReason: 'Located on major traffic route, risk of vehicle damage and accidents.',
    aiSuggestedAction: 'Immediate road patching during low-traffic hours.',
    duplicateOf: null,
    clusterId: 'cl1',
  },
  {
    id: 'CIV-2024-002',
    title: 'Garbage not collected for 5 days',
    description: 'The garbage bin in our lane has not been emptied for 5 days causing foul smell and health concerns.',
    category: 'Garbage',
    location: 'Gandhi Nagar, Lane 3',
    locality: 'Gandhi Nagar',
    lat: 28.6139, lng: 77.2090,
    photoUrl: null,
    status: 'Pending',
    priority: 'Medium',
    department: 'Sanitation',
    assignedOfficer: null,
    deadline: null,
    createdAt: daysAgo(1),
    citizenId: 'c1', citizenName: 'Rahul Mehta',
    updates: [
      { id: 'u3', status: 'Pending', message: 'Complaint registered. Awaiting officer assignment.', timestamp: daysAgo(1), by: 'Civic Pilot AI' },
    ],
    aiCategoryConfidence: 0.93,
    aiPriorityReason: 'Health hazard but confined to single lane, moderate urgency.',
    aiSuggestedAction: 'Schedule immediate garbage collection and increase frequency.',
    duplicateOf: null,
    clusterId: 'cl2',
  },
  {
    id: 'CIV-2024-003',
    title: 'Streetlight not working on Park Street',
    description: 'Three consecutive streetlights are not working on Park Street, area is unsafe at night.',
    category: 'Streetlight',
    location: 'Park Street, Near Town Hall',
    locality: 'Park Street',
    lat: 28.5535, lng: 77.2588,
    photoUrl: null,
    status: 'Resolved',
    priority: 'High',
    department: 'Electrical',
    assignedOfficer: 'Amit Verma',
    deadline: daysAgo(1),
    createdAt: daysAgo(8),
    citizenId: 'c2', citizenName: 'Anita Desai',
    updates: [
      { id: 'u4', status: 'Pending', message: 'Complaint registered and forwarded to Electrical department.', timestamp: daysAgo(8), by: 'Civic Pilot AI' },
      { id: 'u5', status: 'In Progress', message: 'Amit Verma assigned. Replacement parts ordered.', timestamp: daysAgo(6), by: 'Admin Office' },
      { id: 'u6', status: 'Resolved', message: 'All three streetlights replaced and tested. Issue resolved.', timestamp: daysAgo(3), by: 'Amit Verma' },
    ],
    aiCategoryConfidence: 0.98,
    aiPriorityReason: 'Safety concern for night-time pedestrians and vehicles.',
    aiSuggestedAction: 'Replace faulty streetlight units and inspect wiring.',
    duplicateOf: null,
    clusterId: 'cl3',
  },
  {
    id: 'CIV-2024-004',
    title: 'Water leakage from underground pipe',
    description: 'Continuous water leakage near the community water tank, wasting water and creating waterlogging.',
    category: 'Water Leakage',
    location: 'Indira Nagar, Block B',
    locality: 'Indira Nagar',
    lat: 28.5244, lng: 77.1855,
    photoUrl: null,
    status: 'Overdue',
    priority: 'Critical',
    department: 'Water Authority',
    assignedOfficer: 'Sneha Reddy',
    deadline: daysAgo(2),
    createdAt: daysAgo(10),
    citizenId: 'c3', citizenName: 'Vikram Patel',
    updates: [
      { id: 'u7', status: 'Pending', message: 'Complaint registered. Critical priority flagged by AI.', timestamp: daysAgo(10), by: 'Civic Pilot AI' },
      { id: 'u8', status: 'In Progress', message: 'Sneha Reddy assigned. Excavation team dispatched.', timestamp: daysAgo(8), by: 'Admin Office' },
    ],
    aiCategoryConfidence: 0.95,
    aiPriorityReason: 'Water wastage + road damage risk. Overdue deadline.',
    aiSuggestedAction: 'Emergency pipe repair and water supply restoration.',
    duplicateOf: null,
    clusterId: 'cl4',
  },
  {
    id: 'CIV-2024-005',
    title: 'Pothole on Anna Salai main road',
    description: 'Multiple potholes on Anna Salai causing heavy traffic disruption during peak hours.',
    category: 'Potholes',
    location: 'Anna Salai, Near Signal 4',
    locality: 'Anna Salai',
    lat: 28.4326, lng: 77.0410,
    photoUrl: null,
    status: 'Pending',
    priority: 'Critical',
    department: 'Public Works',
    assignedOfficer: null,
    deadline: null,
    createdAt: daysAgo(0),
    citizenId: 'c2', citizenName: 'Anita Desai',
    updates: [
      { id: 'u9', status: 'Pending', message: 'Complaint registered. Critical priority — major road affected.', timestamp: daysAgo(0), by: 'Civic Pilot AI' },
    ],
    aiCategoryConfidence: 0.97,
    aiPriorityReason: 'Major arterial road, heavy traffic, multiple potholes detected.',
    aiSuggestedAction: 'Emergency road repair with traffic diversion plan.',
    duplicateOf: null,
    clusterId: 'cl1',
  },
  {
    id: 'CIV-2024-006',
    title: 'Drainage overflow during rain',
    description: 'Drainage channel overflows onto the road every time it rains, causing waterlogging for 2-3 days.',
    category: 'Drainage',
    location: 'Lajpat Nagar, Block C',
    locality: 'Lajpat Nagar',
    lat: 28.5677, lng: 77.2435,
    photoUrl: null,
    status: 'In Progress',
    priority: 'High',
    department: 'Drainage Board',
    assignedOfficer: 'Mohammed Ali',
    deadline: daysAhead(5),
    createdAt: daysAgo(4),
    citizenId: 'c3', citizenName: 'Vikram Patel',
    updates: [
      { id: 'u10', status: 'Pending', message: 'Complaint registered and forwarded to Drainage Board.', timestamp: daysAgo(4), by: 'Civic Pilot AI' },
      { id: 'u11', status: 'In Progress', message: 'Mohammed Ali assigned. Channel clearing in progress.', timestamp: daysAgo(2), by: 'Admin Office' },
    ],
    aiCategoryConfidence: 0.92,
    aiPriorityReason: 'Recurring waterlogging, public health and traffic risk.',
    aiSuggestedAction: 'Clear drainage channel and install overflow prevention grate.',
    duplicateOf: null,
    clusterId: 'cl5',
  },
  {
    id: 'CIV-2024-007',
    title: 'Garbage overflow near school',
    description: 'Garbage bins near the school are overflowing, attracting stray animals and creating hygiene issues.',
    category: 'Garbage',
    location: 'Gandhi Nagar, Near School',
    locality: 'Gandhi Nagar',
    lat: 28.6200, lng: 77.2100,
    photoUrl: null,
    status: 'Resolved',
    priority: 'Medium',
    department: 'Sanitation',
    assignedOfficer: 'Priya Sharma',
    deadline: daysAgo(2),
    createdAt: daysAgo(6),
    citizenId: 'c1', citizenName: 'Rahul Mehta',
    updates: [
      { id: 'u12', status: 'Pending', message: 'Complaint registered.', timestamp: daysAgo(6), by: 'Civic Pilot AI' },
      { id: 'u13', status: 'In Progress', message: 'Priya Sharma assigned. Additional bins deployed.', timestamp: daysAgo(4), by: 'Admin Office' },
      { id: 'u14', status: 'Resolved', message: 'Bins cleared, collection frequency increased to daily.', timestamp: daysAgo(2), by: 'Priya Sharma' },
    ],
    aiCategoryConfidence: 0.91,
    aiPriorityReason: 'School zone hygiene concern, moderate urgency.',
    aiSuggestedAction: 'Increase collection frequency and add additional bins.',
    duplicateOf: null,
    clusterId: 'cl2',
  },
  {
    id: 'CIV-2024-008',
    title: 'Streetlight flickering near park',
    description: 'Streetlight near the community park flickers all night, residents concerned about safety.',
    category: 'Streetlight',
    location: 'Park Street, Near Park Gate',
    locality: 'Park Street',
    lat: 28.5500, lng: 77.2600,
    photoUrl: null,
    status: 'Pending',
    priority: 'Low',
    department: 'Electrical',
    assignedOfficer: null,
    deadline: null,
    createdAt: daysAgo(0),
    citizenId: 'c2', citizenName: 'Anita Desai',
    updates: [
      { id: 'u15', status: 'Pending', message: 'Complaint registered.', timestamp: daysAgo(0), by: 'Civic Pilot AI' },
    ],
    aiCategoryConfidence: 0.90,
    aiPriorityReason: 'Partial lighting still functional, lower urgency.',
    aiSuggestedAction: 'Replace streetlight bulb during next maintenance round.',
    duplicateOf: null,
    clusterId: 'cl3',
  },
];
